{% set name = 'clinguin' %}
{% set dev = not environ.get('BUILD_RELEASE', false) %}
{% set version = environ.get('VERSION_NUMBER') %}
{% set revision = environ.get('GITHUB_SHA', 'wip') %}
{% set build = environ.get('BUILD_NUMBER', "0") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

requirements:
  host:
  - python >=3.8
  - pip
  run:
  - clingo>=5.6.0
  - clorm>=1.4.1
  - clingo-dl
  - httpx<=0.20.0
  - fastapi==0.103.0
  - pydantic
  - networkx
  - uvicorn
  - httpcore==0.13.3
  - h11==0.12.0
  - clingraph
  - Pillow

build:
  number: {{ build }}
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points: ['clinguin =  clinguin:main']


about:
  home: https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A system to build User Interfaces in ASP
  doc_url: https://clinguin.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/potassco/{{ name }}
