repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.3.0
    hooks:
    - id: autoflake
      args: ["--in-place",  "--imports=clinguin", "--ignore-init-module-imports", "--remove-unused-variables"]
      exclude: ^.github/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^.github/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^.github/

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
      exclude: ^.github/

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    - id: mdformat
      args: ["--wrap", "79"]
      exclude: ^docs/
      additional_dependencies:
      - mdformat-gfm
